name: CI # El nombre del workflow que verás en la pestaña Actions de GitHub

on:
  pull_request:
    branches: [main] # Corre ANTES del merge. Es el disparador que alimenta al gate bloqueando PRs rotos
  push:
    branches: [main] # Corre DESPUÉS del merge a main. Actualiza el badge en el README y deja el caché base para futuros PRs

jobs:
  build-backend: # Este ID exacto es el que debes escribir al configurar el "Required status check" en GitHub
    runs-on: ubuntu-latest # Ejecuta en una máquina virtual Linux limpia y efímera prestada por GitHub
    steps:
      - name: Qué estamos verificando
        env:
          # Construye el nombre de la rama correctamente en el contexto de un PR (evita que diga "numero/merge")
          RAMA: ${{ github.head_ref || github.ref_name }} 
        run: echo "Rama $RAMA · commit $GITHUB_SHA"

      - name: Bajar el código al runner
        uses: actions/checkout@v6 # Clona tu repositorio en la máquina virtual. Sin esto, no hay archivos para construir

      - name: Preparar el constructor que sabe cachear
        uses: docker/setup-buildx-action@v4 # Cambia el constructor por defecto de Docker por uno que sabe enviar capas al almacén de GitHub

      - name: Construir la imagen del backend
        uses: docker/build-push-action@v7
        with:
          context: ./backend # Apunta a la carpeta donde vive el Dockerfile del backend
          push: false # Evita publicar la imagen en un registry; el TP4 solo pide verificar que construya
          tags: backend:ci # Nombre temporal de la imagen mientras vive en el runner
          cache-from: type=gha,scope=backend # Trae las capas previamente cacheadas desde GitHub Actions
          # Guarda todas las capas generadas (mode=max). 
          # El 'scope=backend' es vital para que no pise el estante del frontend en el almacén
          cache-to: type=gha,mode=max,scope=backend 

  build-frontend: # Al estar al mismo nivel que build-backend, corre en paralelo en otra máquina
    runs-on: ubuntu-latest
    steps:
      - name: Qué estamos verificando
        env:
          RAMA: ${{ github.head_ref || github.ref_name }}
        run: echo "Rama $RAMA · commit $GITHUB_SHA"

      - name: Bajar el código al runner
        uses: actions/checkout@v6

      - name: Preparar el constructor que sabe cachear
        uses: docker/setup-buildx-action@v4

      - name: Construir la imagen del frontend
        uses: docker/build-push-action@v7
        with:
          context: ./frontend
          push: false
          tags: frontend:ci
          cache-from: type=gha,scope=frontend # Usa su propio scope exclusivo para no mezclar capas con el backend
          cache-to: type=gha,mode=max,scope=frontend